### ISSUE TITLE
NEO (http://build-oracc.museum.upenn.edu:4300/home) is not accessible

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#101]
Enter the NEO beta-version URL ([http://build-oracc.museum.upenn.edu:4300/home](url)) into a web browser. 
**Expected result:**
([http://build-oracc.museum.upenn.edu:4300/home](url)) should load the beta-version of NEO, which should be available to users for feedback.
**Actual result:**
Page fails to load on multiple browsers. I have tested on Safari and Firefox from multiple computers. See the screenshots below
![safari](https://user-images.githubusercontent.com/19565350/44020364-f12171b6-9ee1-11e8-86d7-3df4aea6378b.png)
![firefox](https://user-images.githubusercontent.com/19565350/44020366-f2ad18f0-9ee1-11e8-85a5-2c8757862e87.png)

**Comment by ageorgou** [comment]
Hi @jnovotny-lmu,

Thanks for bringing this to our attention, and apologies for not replying sooner (various members have been on holiday). The website should now be up and running again -- please tell us if it doesn't work for you.

We'll be looking into monitoring it and ensuring it is always up as we expand and improve the search funcationality in the coming weeks. Do please let us know if you notice any other problems, or if you have any comments or suggestions, either here or, preferably, at https://github.com/oracc/oracc-search-front-end/issues.

**Comment by stinney** [comment]
Closing this one; do please report any further issues concerning this at the URL mentioned by ageorgou above.
