### ISSUE TITLE
Print Text option not in CMAWRo Item View

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#103]
For example, go to [http://oracc.museum.upenn.edu/cmawro/corpus](url) and open any text.
Expected result:
In left pane, under Views, there should be a  "Print Text" link.
Actual result:
No "Print Text" link is available for any text in CMAWRo. This option is available for all other projects.

**Comment by stinney** [comment]
CMAWRo now uses the standard outline pane instead of a very old custom one which was still present in the cmawro web directory; Print is now listed.  While I was at it, I secretly fixed the stray bullet point in Numbers bug that has been nagging a few of us for a while.
