### ISSUE TITLE
Catalogue pager searches fail in P-driven and Score-driven projects

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#11]
Here is the original report by Jamie:
I have been trying to get RIBo ready for public viewing. I spent a bit of time last week drafting a page on searching the corpus using the catalogue. See [http://oracc.museum.upenn.edu/ribo/babylon7/usingtheribocorpus/index.html](url)
The catalogue functionality works pretty well on the various projects with Q-number composites: ribo/babylon7, rinap, rinap/rinap1, rinap/rinap3, rinap/rinap4.
For example, object_type:prism yield results.
However, I have yet to perform a success catalogue search in various scores projects and sources projects.
These are:
[http://oracc.museum.upenn.edu/rinap/scores/pager](url)
[http://oracc.museum.upenn.edu/rinap/sources/pager](url)
[http://oracc.museum.upenn.edu/ribo/sources/pager](url)
[http://oracc.museum.upenn.edu/ribo/bab7scores/pager](url)

All have local XML catalogues in their 00cat folders. For example, the ribo/bab7scores catalogue data was extracted from the ribo/babylon7 catalogue, so the search functionality should work for both projects.

For example, in ribo/bab7scores enter ruler:nabopolassar or object:cylinder into the search box. From the Page View, it is clear that these should yield results, but they do not. Either this is a bug or I do not have the correct data in the config.xml files. I attach the config.xml for ribo/bab7scores and ribo/sources. Please advise whether the config need the correct lines or whether this is a bug.

**Comment by stinney** [comment]
Fixed.
