### ISSUE TITLE
Cuneified and Buy the Book links do not work in Item View

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#17]
**Steps:**
1. For example, go to [http://oracc.museum.upenn.edu/rinap/rinap1/pager](url).
2. Open any text. 
3. Under Views in the left pane, click on the Cuneified or Buy the Book link.

_Expected results_
The pager should open a pop-up box display the cuneified text (in the case of clicking on the Cuneified button) or open the URL specified in the config.xml (in the case of clicking on the Buy the Book link).

_Actual result_
The pager does not open a pop-up box or new window. Nothing happens when clicking on the two links.

The rinap/rinap1/config.xml has `<option name="views-cuneify" value="true"/><option name="views-buy-book" value="http://www.eisenbrauns.com/item/TADROYALI"/>`

**Comment by jnovotny-lmu** [comment]
I have tested this in both Safari and Firefox. In box cases I have verify that pop-up boxes are not being blocked.

**Comment by stinney** [comment]
Both fixed.

**Comment by jnovotny-lmu** [comment]
@stinney 
Thanks for fixing this. The functionality now works in Firefox, but not in Safari Version 10.0 (11602.1.50.0.10); I have verified again that "Block pop-up window" is disabled. Thus, re-opening.

**Comment by jnovotny-lmu** [comment]
I have tested the functionality on an older version of Safari (Version 5) and both features work.

**Comment by jnovotny-lmu** [comment]
Oddly, the  functionality now works in Safari Version 10.0 (11602.1.50.0.10); at least after rebuilding the project with View TEI.  However, in Safari, the default cuneiform script is Old Babylonian, not Neo-Assyrian. In Firefox, the script is Neo-Assyrian. The error persists even if I remove the OB font from my font library. When testing on Safari 5 and on my mobile device, neither of which had the cuneiform fonts installed, the default was the OB script.

**Comment by jnovotny-lmu** [comment]
Closing bug since pop-up boxes are working in Safari 10.0. Moving comments on cuneified to new bug.
