### ISSUE TITLE
Bad search results for Sumerian texts:

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#32]
Search is unpredictable for transliteration [find examples] lugal-sze produces bad results.

_Reporter's comments:_
This was copied from the original blog post. Details may need to be clarified by the original reporter (not named in the Blog post, by presumably Niek).

**Comment by stinney** [comment]
This is fixed; Niek helped line up reproducible results and the fix is part of a handful of improvements to the way that searching from the p3 search box works as well as the way lem indexing is done.
