### ISSUE TITLE
Emacs checker debugger fails

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#42]
in Emacs checker frequently fails (goes into debugging mode or produces an error message)        wrong type char-or-p; happening for about two months pager-translations -- has this been superceded by automated computation in P3?

_Reporter's comments:_
This was copied from the original blog post. Details may need to be clarified by the original reporter (not named in the Blog post).

**Comment by stinney** [comment]
Closing because Emacs
