### ISSUE TITLE
Cams/tlab: proxied material doesn’t create links in online glossaries

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#53]
Cams/tlab – proxied material always stays in new and doesn’t create links to instances

_Reporter's comments:_
This was copied from the original blog post. Details may need to be clarified by the original reporter (not named in the Blog post, presumably Eleanor).

**Comment by stinney** [comment]
Believed fixed

**Comment by stinney** [comment]
Confirmed fixed after working on cmawro reorg
