### ISSUE TITLE
COFs generate wrong output

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#54]
COFs generate wrong output in *.new, putting one $ and no parens

_Reporter's comments:_
This was copied from the original blog post. Details may need to be clarified by the original reporter (not named in the Blog post).

**Comment by stinney** [comment]
I believe this is fixed so I am tagging it as low priority for now just to make sure it doesn't disappear completely

**Comment by stinney** [comment]
I've seen no new reports of this so I'm closing it.
