### ISSUE TITLE
Print text option not fully functional in projects that have multi-language translations

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#58]
The "print text" option only allows users to print English translations in projects that have more than one language for a text's translation. For example, Spanish in BabRiT and Italian in eCUT. 

**_Steps to reproduce_**
1. Go to [http://oracc.museum.upenn.edu/babrit/P363710/](url).
2. Change the language from English to Spanish..
3. Click on Print Text. 

_Actual results_
The pager loads a new window. The translation shown is English.

_Expected results_
The pager should load the Spanish translation since that language had been selected manually by the user.

**Comment by stinney** [comment]
Fixed.
