### ISSUE TITLE
Issues with searching Old Persian texts in the Oracc pager

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#60]
While working on ARIo [http://oracc.museum.upenn.edu/ario/pager](url), we have come across several issues with searching the transliterations of Old Persian texts. At this time, three issues have been observed.

1. _Search only finds whole words_
For example, if one looks for `x-š-a-y-θ-i-y`, the system will return results if one searches for `xšayθiy` (note that one must remove the hyphens in the search). However, if one searches for `ay`, only whole words with `a-y` will be returned; `xšayθiy` will not appear in the search results.

2. _Search fails on logographic writings_
There is no way to search for the following logographic writings: `XŠ`, `AM` and `AM2`.

3. _Search fails on words broken over two lines_
Old Persian texts very frequently divide words over two lines. The search fails to return results when the word is broken over two lines. For example, if a text has `x-š-a-y-θ-i-y` split -- for example,  `x-š-a-y-θ-` in one line and `i-y` in the next, the search fails; it will work if one searches for `xšayθ` or `iy`, which it then regards as whole words (see no. 1 above). I have tried coding a semi-colon into the ATF files at the break, but the search still fails. The search even fails for sentence searches since the Oracc processor adds a blank space at the end of the line and, thus, `xšayθiy` fails because `x-š-a-y-θ;-i-y` is rendered as `x-š-a-y-θ -i-y`.

It is unclear whether these should be classified as a bug or an enhancement.

**Comment by stinney** [comment]
@jnovotny-lmu I just fixed these issues.
