### ISSUE TITLE
CMAwRo online glossary displays ghost/non-existant attestations with dead links

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#62]
A representative example of the glossary page creating ghost/non-existant attestations with dead links can be found in CMAwRo. These appear with normalised forms displayed (of words that appear in PSUs). E.g., go to [http://oracc.museum.upenn.edu/cmawro/cbd/akk/M.html](url) and scroll down to _muhhu_.
See <img width="730" alt="screen shot 2016-12-11 at 7 16 09 am" src="https://cloud.githubusercontent.com/assets/19565350/21078492/c6c5db2e-bf71-11e6-8374-ed76b7ebcb09.png">. None of these forms exist in the CMAwRo glossary. I attach the akk.glo for verification; I have converted it to a text file.
[akkglo.txt](https://github.com/oracc/oracc/files/644259/akkglo.txt)
Just scrolling through the letter M, the same issue occurs, for example, occurs, with the words _magarru_, _mahru_, _māmītu_, and _miqtu_,

The common feature of this is that all forms are now combined with the word _lemuttu_. However, this is not the case in the `akk.glo` (see the attached file). As far as I can tell, the processor is adding _lemuttu_ to all PSUs in the CMAwRo online glossary. In every case, the link opens a blank/all white window (=dead link). 

This is regarded as a `high priority` bug since it severely reduces the user-friendliness of CMAwRo.

**Comment by stinney** [comment]
This is fixed.
