### ISSUE TITLE
Sign Division Problem

### ISSUE THREAD

**Issue by D-K-E** [oracc/oracc#65]
Hi,
As i have stated in the issue #61 , some elamite texts rarely contain divided signs. Now, as far as i know Grapheme Description Language covers all there is to know about the ATF. However i can't seem to find any information with regard to how to encode this phenomenon. If it is not covered in the GDL, i would like propose the inclusion of the newline character to complex sign notation, the operator sign should be retained with the first part of division for facilitating the algorithm that handles other divided entities. The overall look of the character on the c-atf would be something like the following:    
|KAx\n34. KA|     
Thus if i replicate the view in markdown:
33. something ancient something old something waayy ancient in a cool way |KAx     
34. KA| other cool ancient things cool ancient formula, something ancient etc.     

All the Best

**Comment by stinney** [comment]
@D-K-E -- I'm closing this one as well because split words now work as documented in ATF as processed on Oracc.  Thanks very much for taking the time to report this issue.
