### ISSUE TITLE
Interlinear translations not appearing online

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/oracc#69]
Susanne Paulus is keen to add her kudurru-corpus to Oracc — hurrah! — and I am currently playing with a test file at http://oracc.museum.upenn.edu/cams/misc/X000000

The least labour-intensive solution was to make the translations interlinear, thus:

&X000000 = Kadašman-Ḫarbe I. 1 (KḪ I 1)

#project: cams/misc
#atf: use math
#atf: use legacy
#atf: use unicode
#atf: lang akk-x-midbab

@object kudurru

@column 1
1.	e-nu-um 
#tr.de: Als

The file is valid and the corpus builds, but the translation is not appearing at http://oracc.museum.upenn.edu/cams/misc/X000000. What am I doing wrong?

**Comment by stinney** [comment]
I think this is a bug; I'll look at it harder over the weekend.  For now please assume that you are not doing anything wrong :)

**Comment by EleanorRobson** [comment]
Fixed! closing this issue.
