### ISSUE TITLE
Pager duplicates written forms for PSUs

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#7]
For all PSUs, the pager displays the written form double. 
For example, on [http://oracc.museum.upenn.edu/cmawro/cbd/akk/K.html](url) the written forms for _kirbān eqli_ as displayed as 
`kirbān eqli ['FIELD-CLOD'-PLANT] (N) 
Written forms: (*) (*) ; úLAG.A.ŠÀ úLAG.A.ŠÀ; úLAG.A.ŠÀ.GA úLAG.A.ŠÀ.GA; úLAG.AŠA₅ úLAG.AŠA₅. 
Normalized forms: kirbān eqli ( (*) (*) , úLAG.A.ŠÀ úLAG.A.ŠÀ, úLAG.A.ŠÀ.GA úLAG.A.ŠÀ.GA, úLAG.AŠA₅ úLAG.AŠA₅). 
1. 'field-clod'-plant`

The expected result is that each written form should be displayed only once.
The corresponding entry in the glossary file has:

`@entry kirbān eqli ['field-clod'-plant] N
@parts kirbānu[lump (of earth)]N eqlu[field]N
@form  * %akk/n $kirbān $eqli
@form  {u₂}LAG.A.ŠA₃ $kirbān $eqli
@form  {u₂}LAG.A.ŠA₃.GA $kirbān $eqli
@form  {u₂}LAG.AŠA₅ $kirbān $eqli
@sense N 'field-clod'-plant
@end entry`

Other examples in CMAQRO include: bēl dabābi, bēl awāti, ana libbi and many more. Greta reports "Even worse is the situation with muhhu which lists more than a page (!) of written forms and a near eternal list of normalized forms. No idea what is wrong here. Also ana, libbu and others."

**Comment by stinney** [comment]
Fixed.
