### ISSUE TITLE
ESP build replaces em-dash and en-dash with hyphen

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/oracc#70]
Until now this has just been a minor irritant in the Electrostatic legacy — it dates from the days, centuries ago, when George was concerned about browser support for non-ascii punctuation. But now Heather properly needs em-dashes for PNAo, as word separators in transliterated PNs (// SAAo and GKAB). 

We now need to:
* comment out the lines of code in the ESP build programme that convert "—" and "–" to " - "
* add code that converts "--" to "—" (the work-around that many portal sites have used for em-dash as punctuation).

**Comment by stinney** [comment]
Both requests are now implemented; please try it out and let me know of any problems.

Note that the auto-conversion of eN-dashes only works if there are digits either side.

**Comment by EleanorRobson** [comment]
Fantastic, thanks so much for dealing with this so fast! Just rebuilt PNAo and em-dashes are go :) I’m delighted and I’m sure Heather will be too.

Cheers,



e
--

Eleanor Robson
Professor of Ancient Middle Eastern History
History Department, University College London
Gower Street, London WC1E 6BT, UK
e.robson@ucl.ac.uk<mailto:e.robson@ucl.ac.uk> • office: 020 7679 1337




On 12 Sep 2017, at 11:52, stinney <notifications@github.com<mailto:notifications@github.com>> wrote:


Both requests are now implemented; please try it out and let me know of any problems.

Note that the auto-conversion of eN-dashes only works if there are digits either side.

**Comment by EleanorRobson** [comment]
Brilliant! Many thanks,
Heather
