### ISSUE TITLE
text lists

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/oracc#72]
Is the documentation at http://oracc.museum.upenn.edu/doc/help/managingprojects/projects/#h_textlists wrong/out of date?

In cams/tlab I'm trying to make week-by-week lists of texts for class which I can use to link to from Moodle, putting them in 00lib/lists as described above. But when I type, e.g., 

oracc.org/cams/tlab/week01

I get a 500 Internal Server Error message in return. What's going wrong?

**Comment by stinney** [comment]
It is correct.  If a list file has ^M characters instead of or as well as ^J for end of line it breaks--users shouldn't have to worry about this so I'm modifying the installation to fix this now.  Take a look at http://oracc.org/cams/tlab/w1 for a list I corrected manually.

**Comment by EleanorRobson** [comment]
Ah splendid, thanks!

**Comment by stinney** [comment]
The installation now converts ^M to ^J and reduces sequences of ^J to a single ^J.

**Comment by EleanorRobson** [comment]
This problem has reappeared: my new lists for this coming term (e.g., http://oracc.museum.upenn.edu/cams/tlab/week11) are failing, although made the same way as the old.

**Comment by stinney** [comment]
OK, similar symptom but different underlying cause--00lib/lists was being packed and built properly for oracc build corpus, but not for oracc build.  Fixed.
