### ISSUE TITLE
s: and l: searches in pager and glossaries fail to display proper results

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#9]
The issues were reported by Greta in [http://oracc.museum.upenn.edu/cmawro/pager](url)

**EXAMPLE 1**
**From the pager**
1. Open [http://oracc.museum.upenn.edu/cmawro/pager](url)
2. Enter s:KAL in the search bar and click the search button.

_Expected results_
The Pager should display search results

_Actual Results_
Pager displays blank files (see the attachment).
![bug 1](https://cloud.githubusercontent.com/assets/19565350/17096254/ba4363e8-5258-11e6-8e9c-5d694b9519e3.png)

**EXAMPLE 2**
**From the pager**
1. Open [http://oracc.museum.upenn.edu/cmawro/pager](url)
2. Enter s:UD or l:UD in the search bar and click the search button.

_Expected results_
The Pager should display search results, including logographic writings.

_Actual Results_
Syllabic readings with ud and tú in Akkadian + Sumerian attestations are displayed. However, all logographic writings are omitted.

**EXAMPLE 3**
**From the Akkadian glossary**
1. Open [http://oracc.museum.upenn.edu/cmawro/akk](url)
2. Enter s:UD into the search bar and click the search button.

_Expected results_
The Pager should display search results, including logographic writings.

_Actual Results_
Only lemma’s with spellings with ud, no other readings, are displayed.

**EXAMPLE 3**
1. Open [http://oracc.museum.upenn.edu/cmawro/akk](url)
2. Enter l:UD into the search bar and click the search button.

_Expected results_
The Pager should display search results of l:UD.
_Actual Results_
The pager displays no results.

**Comment by jnovotny-lmu** [comment]
A few additional comments/observations noted on this bug (10 December 2016).
**A. Pager fails to display information from data appearing in witness transliteration lines of scores**
The Oracc search function appears to be able to find data that appears in the witness lines of scores. For example, one should be able to find _mu-ur-du-da-a_ if that string is added to the search window. That spelling, appears in one of the witnesses of [http://oracc.museum.upenn.edu/cmawro/Q004184/](url). See the screenshot below:
<img width="711" alt="screen shot 2016-12-11 at 7 40 31 am" src="https://cloud.githubusercontent.com/assets/19565350/21078589/2b424be8-bf75-11e6-9981-abdc30fb209a.png">
The issue, as far as I can tell, is that the corresponding ATF line is a witness line in a score, and not the main line. Because CMAwRo uses normalisations in its composite lines and transliterations for its witness lines, therefore searches for transliterations will always fail. Thus, the search function in the Oracc pager should be enabled to search through witness lines.

**B. Pager search function is unable to search normalisations in transliterations**
At present, as far as I can see, Oracc cannot search normalisations that appear in the transliterations. For example, if one enters _suādū_ or _suadu_ into the search window, no results are displayed. That word is normalised in line 1.1.1:2′ of [http://oracc.museum.upenn.edu/cmawro/Q004184/](url). It should be possible to search normalised forms.

**C. Pager search function fails in Akkadian glossary** 
For example, go to [http://oracc.museum.upenn.edu/cmawro/akk](url). If one types `muh`, the result _muhhu_ appears. However, if one types in `muhhu`, not results appear; one **expects** the entry for _muhhu_ (at the very least). If one types in `muḫḫu`, the following appears:
<img width="795" alt="screen shot 2016-12-11 at 7 54 13 am" src="https://cloud.githubusercontent.com/assets/19565350/21078640/121766b0-bf77-11e6-95e1-f4eb6e067389.png">.
Some how, the double `h` causes a problem. If one types in `palhu`, no results are displayed. 
The issue is connected with `h/ḫ` and double `hh/ḫḫ`. If one enters `ḫ` searches work. However, with `h', they fail. As far as I can tell, everything entered as a normal `h` in the Akkadian search window fails.

**Comment by jnovotny-lmu** [comment]
RE: **C. Pager search function fails in Akkadian glossary**
The issue occurs only in glossaries that have `ḫ` in the dataset. If `h` is used, there is no issue in searching forms with `h` and `hh`.

**Comment by stinney** [comment]
I have fixed all of these except C, which I consider a feature.  Most glossaries do not use ḫ; where a glossary does use it, it can be searched properly by entering ḫ in the search box.
