### ISSUE TITLE
Glossaries are missing on the RINAP hub page and link to other page issues

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#94]
The glossaries are missing on the RINAP Hub page; see [http://oracc.museum.upenn.edu/rinap/hub.html](url).
**Expected result:** The Akkadian and various QPN glossaries are accessible via the hub page.
**Actual result:** The glossaries are not publicly accessible.
Moreover, the following links display errors:
Oracc documentation [http://oracc.museum.upenn.edu/doc2/help/](url)
rinap Advanced Search [http://oracc.museum.upenn.edu/rinap/as](url)
Transliterated Texts [http://oracc.museum.upenn.edu/rinap/withatf](url)
Lemmatised Texts [http://oracc.museum.upenn.edu/rinap/withlem](url)

**Comment by jnovotny-lmu** [comment]
In addition, none of the links in the Proper Noun glossaries work. If one clicks on any link, a blank pop-up box appears.

**Comment by stinney** [comment]
This is fixed.
