### ISSUE TITLE
Core Resource issues on RIBo and SAAo

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#95]
The following problems occur on the RIBo hub page [http://oracc.museum.upenn.edu/ribo/hub.html](url)
Transliterated Texts: One of 209 texts is partially displayed; see [http://oracc.museum.upenn.edu/ribo/withatf](url)
Lemmatised Texts:  One of 209 texts is partially displayed; see [http://oracc.museum.upenn.edu/ribo/withlem](url)
As far as I can tell, these issues are only happening with the top-level umbrella projects. Compare SAAo Core Resources [http://oracc.museum.upenn.edu/saao/hub.html](url), which fails to display any lemmatised texts when one clicks on the Lemmatised Text link.

**Comment by stinney** [comment]
I believe this is fixed; please reopen it if not.
