### ISSUE TITLE
lemmatisation fails when name has -- and a logographic element

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#98]
The ATF processor generates an error when a name (PSU) contains **BOTH `--` and logographic name element**. For example, saao/saa01/SAA01_01.atf:14 has `{1}asz-szur*--MAN--PAB#`. The error reads: `SAA01_01.atf:14: (lem) no FORM `{1}aš-šur-MAN—PAB'; 1 match for Aššur-šarru-uṣur[1]PN in glossary saao/saa01:akk-x-neoass`.

The ATF processor interprets the `--` (for lemmatisation purposes) after the logographic name element as  `—` (em-dash) rather than `-` (single hyphen). As many names (and PSUs) in SAAo have **BOTH `--` and logographic name element**, the  lemmatisation for numerous PSUs and names fails. As a result, these lemmatised words and names do not appear in the online glossaries, the words/names are not lemmatised in the annotated editions (no hyperlink), and the lemmatisation data is not included in the JSON output.

I am marking this bug as high priority as I need this fixed before the LMU-UCB workshop (starting July 7th) as much of the conversation enters around the JSON data. At present, this issue is restricted to SAAo (all subprojects). As SAAo is the most used project (with text corpora), it is important that this issue be addressed ASAP. Many thanks.
 
I believe the bug resulted from the correction of [https://github.com/oracc/oracc/issues/89](url)

**Comment by jnovotny-lmu** [comment]
Any progress on the correction of this bug?

**Comment by stinney** [comment]
Closing because no recent reports that this is an issue since I fixed it.
